class KlineProps:
    TIME_OPEN = "time_open"
    OPEN = "open"
    HIGH = "high"
    LOW = "low"
    CLOSE = "close"
    VOLUME = "volume"


class Indicators:
    BOLL_UP = "boll_up"
    BOLL_MID = "boll_mid"
    BOLL_LOW = "boll_low"
    EMA_SHORT = "ema_short"
    EMA_MID = "ema_mid"
    EMA_LONG = "ema_long"
    SMA_SHORT = "sma_short"
    SMA_MID = "sma_mid"
    SMA_LONG = "sma_long"
    TYPICAL_PRICE = "typical_price"
    ADX = "adx"
    CCI = "cci"
    MACD = "macd"
    MACD_SIGNAL = "macd_signal"
    MACD_HIST = "macd_hist"
    RSI = "rsi"
    ROC = "roc"
    STOCH_RSI_FASTK = "stoch_rsi_fastk"
    STOCH_RSI_FASTD = "stoch_rsi_fastd"
    WILL_R = "will_r"
    OBV = "obv"
